# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtWidgets, QtGui, QtCore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 705)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))  # Позволяем максимизацию
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))  # Устанавливаем минимальный размер окна
        MainWindow.setWindowFlags(
                QtCore.Qt.Window | QtCore.Qt.WindowMinMaxButtonsHint | QtCore.Qt.WindowCloseButtonHint)
        MainWindow.setStyleSheet("#MainWindow{ \n"
"background-color:#F0F0F0;}\n"
"#Header, #MainBody{ \n"
"background-color:white;}\n"
"#pushButton{\n"
"background-color: transparent;\n"
"color: white;\n"
"text-aligin: center;\n"
"}\n"
"QPushButton{\n"
"text-align:left;\n"
"padding:3px 5px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;}\n"
"QLineEdit{\n"
"background-color:#F0F0F0;\n"
"padding:5px 10px;\n"
"border-radius: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 50)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QWidget(self.centralwidget)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LogoTopBar = QtWidgets.QFrame(self.Header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoTopBar.sizePolicy().hasHeightForWidth())
        self.LogoTopBar.setSizePolicy(sizePolicy)
        self.LogoTopBar.setStyleSheet("background-color:#207BFF;")
        self.LogoTopBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogoTopBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogoTopBar.setObjectName("LogoTopBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.LogoTopBar)
        self.horizontalLayout_4.setContentsMargins(10, 0, 44, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Menu = QtWidgets.QPushButton(self.LogoTopBar)
        self.Menu.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")
        self.Menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/img/Navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.setIcon(icon)
        self.Menu.setIconSize(QtCore.QSize(24, 24))
        self.Menu.setObjectName("Menu")
        self.horizontalLayout_4.addWidget(self.Menu)
        self.Logotip = QtWidgets.QLabel(self.LogoTopBar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Logotip.setFont(font)
        self.Logotip.setStyleSheet("color: white;")
        self.Logotip.setObjectName("Logotip")
        self.horizontalLayout_4.addWidget(self.Logotip)
        self.horizontalLayout.addWidget(self.LogoTopBar, 0, QtCore.Qt.AlignLeft)
        self.TopBar = QtWidgets.QFrame(self.Header)
        self.TopBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBar.setObjectName("TopBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TopBar)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Name = QtWidgets.QLabel(self.TopBar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        self.Name.setFont(font)
        self.Name.setStyleSheet("color:#474A51;")
        self.Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Name.setObjectName("Name")
        self.horizontalLayout_3.addWidget(self.Name)
        self.Person = QtWidgets.QPushButton(self.TopBar)
        self.Person.setSizeIncrement(QtCore.QSize(0, 0))
        self.Person.setStyleSheet("""
    QPushButton {
        background-color: transparent;
    }
    QPushButton:hover {
        background-color: lightgray;
    }
    QPushButton:pressed {
        background-color: gray;
    }
""")
        self.Person.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/img/Person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Person.setIcon(icon1)
        self.Person.setIconSize(QtCore.QSize(32, 32))
        self.Person.setObjectName("Person")
        self.horizontalLayout_3.addWidget(self.Person)
        self.Exit = QtWidgets.QPushButton(self.TopBar)
        self.Exit.setStyleSheet("""
    QPushButton {
        background-color: transparent;
    }
    QPushButton:hover {
        background-color: lightgray;
    }
    QPushButton:pressed {
        background-color: gray;
    }
""")
        self.Exit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/img/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon2)
        self.Exit.setIconSize(QtCore.QSize(20, 20))
        self.Exit.setObjectName("Exit")
        self.horizontalLayout_3.addWidget(self.Exit)
        self.horizontalLayout.addWidget(self.TopBar, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.Header, 0, QtCore.Qt.AlignTop)
        self.MainBody = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody.sizePolicy().hasHeightForWidth())
        self.MainBody.setSizePolicy(sizePolicy)
        self.MainBody.setMinimumSize(QtCore.QSize(800, 487))
        self.MainBody.setObjectName("MainBody")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainBody)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftMenu = QtWidgets.QWidget(self.MainBody)
        self.LeftMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.LeftMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.LeftMenu.setStyleSheet("background-color: #207BFF;")
        self.LeftMenu.setObjectName("LeftMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LeftBar = QtWidgets.QWidget(self.LeftMenu)
        self.LeftBar.setMinimumSize(QtCore.QSize(200, 467))
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout_4.setContentsMargins(-1, -1, 11, 11)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LeftBarUp = QtWidgets.QFrame(self.LeftBar)
        self.LeftBarUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftBarUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftBarUp.setObjectName("LeftBarUp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LeftBarUp)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Report = QtWidgets.QPushButton(self.LeftBarUp)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Report.setFont(font)
        self.Report.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/img/Magazine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Report.setIcon(icon3)
        self.Report.setIconSize(QtCore.QSize(16, 16))
        self.Report.setObjectName("Report")
        self.verticalLayout_5.addWidget(self.Report)
        self.Lab = QtWidgets.QPushButton(self.LeftBarUp)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Lab.setFont(font)
        self.Lab.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")

        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/img/Lab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Lab.setIcon(icon4)
        self.Lab.setIconSize(QtCore.QSize(16, 16))
        self.Lab.setObjectName("Lab")
        self.verticalLayout_5.addWidget(self.Lab)
        self.Statistics = QtWidgets.QPushButton(self.LeftBarUp)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Statistics.setFont(font)
        self.Statistics.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("static/img/Statistic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Statistics.setIcon(icon5)
        self.Statistics.setIconSize(QtCore.QSize(20, 20))
        self.Statistics.setObjectName("Statistics")
        self.verticalLayout_5.addWidget(self.Statistics)
        self.verticalLayout_4.addWidget(self.LeftBarUp)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.LeftBarDown = QtWidgets.QFrame(self.LeftBar)
        self.LeftBarDown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftBarDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftBarDown.setObjectName("LeftBarDown")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.LeftBarDown)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Help = QtWidgets.QPushButton(self.LeftBarDown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Help.setFont(font)
        self.Help.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("static/img/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help.setIcon(icon6)
        self.Help.setIconSize(QtCore.QSize(16, 16))
        self.Help.setObjectName("Help")
        self.verticalLayout_6.addWidget(self.Help)
        self.Settings = QtWidgets.QPushButton(self.LeftBarDown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Settings.setFont(font)
        self.Settings.setStyleSheet("""
    QPushButton {
        background-color: transparent;
        color: white;
    }
    QPushButton:hover {
        background-color: #1E71EA;
        color: white;
    }
    QPushButton:pressed {
        background-color: #1E71EA;
        color: white;
    }
""")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("static/img/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon7)
        self.Settings.setIconSize(QtCore.QSize(16, 16))
        self.Settings.setObjectName("Settings")
        self.verticalLayout_6.addWidget(self.Settings)
        self.verticalLayout_4.addWidget(self.LeftBarDown)
        self.verticalLayout_2.addWidget(self.LeftBar)
        self.horizontalLayout_2.addWidget(self.LeftMenu)
        self.mainBodyContent = QtWidgets.QWidget(self.MainBody)
        self.mainBodyContent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainBodyContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainBodyContent)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ReportpagePatients = QtWidgets.QWidget()
        self.ReportpagePatients.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ReportpagePatients.setObjectName("ReportpagePatients")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ReportpagePatients)
        self.verticalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.TablePatients = QtWidgets.QWidget(self.ReportpagePatients)
        self.TablePatients.setObjectName("TablePatients")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.TablePatients)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Label = QtWidgets.QLabel(self.TablePatients)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Label.setFont(font)
        self.Label.setStyleSheet("color:#474A51;")
        self.Label.setObjectName("Label")
        self.verticalLayout_10.addWidget(self.Label)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLineEdit = QtWidgets.QLineEdit(self.TablePatients)
        self.searchLineEdit.setFixedHeight(40)
        self.searchLineEdit.setFixedWidth(500)
        self.searchLineEdit.setStyleSheet("QLineEdit { margin-top: 10px; }")
        self.searchLayout.addWidget(self.searchLineEdit)
        self.searchLayout.setAlignment(self.searchLineEdit, QtCore.Qt.AlignLeft)
        self.verticalLayout_10.addLayout(self.searchLayout)
        self.TopBarRight = QtWidgets.QFrame(self.TablePatients)
        self.TopBarRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarRight.setObjectName("TopBarRight")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.TopBarRight)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Edit = QtWidgets.QPushButton(self.TopBarRight)
        self.Edit.setText("")
        self.Edit.setStyleSheet("""
            QPushButton {
                background-color: transparent;
            }
            QPushButton:hover {
                background-color: lightgray;
            }
            QPushButton:pressed {
                background-color: gray;
            }
        """)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("static/img/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Edit.setIcon(icon8)
        self.Edit.setIconSize(QtCore.QSize(24, 24))
        self.Edit.setObjectName("Edit")
        self.horizontalLayout_7.addWidget(self.Edit)
        self.Delete = QtWidgets.QPushButton(self.TopBarRight)
        self.Delete.setMinimumSize(QtCore.QSize(0, 0))
        self.Delete.setText("")
        self.Delete.setStyleSheet("""
            QPushButton {
                background-color: transparent;
            }
            QPushButton:hover {
                background-color: lightgray;
            }
            QPushButton:pressed {
                background-color: gray;
            }
        """)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("static/img/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete.setIcon(icon9)
        self.Delete.setIconSize(QtCore.QSize(24, 24))
        self.Delete.setObjectName("Delete")
        self.horizontalLayout_7.addWidget(self.Delete)
        self.verticalLayout_10.addWidget(self.TopBarRight, 0, QtCore.Qt.AlignRight)
        self.TopBarLeft = QtWidgets.QFrame(self.TablePatients)
        self.TopBarLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarLeft.setObjectName("TopBarLeft")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.TopBarLeft)
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Table1 = QtWidgets.QPushButton(self.TopBarLeft)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Table1.setFont(font)
        self.Table1.setStyleSheet("color:#474A51;")
        self.Table1.setObjectName("Table1")
        self.horizontalLayout_11.addWidget(self.Table1, 0, QtCore.Qt.AlignLeft)
        self.Table2 = QtWidgets.QPushButton(self.TopBarLeft)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Table2.setFont(font)
        self.Table2.setStyleSheet("color:#474A51;")
        self.Table2.setObjectName("Table2")
        self.horizontalLayout_11.addWidget(self.Table2, 0, QtCore.Qt.AlignLeft)
        self.Table3 = QtWidgets.QPushButton(self.TopBarLeft)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Table3.setFont(font)
        self.Table3.setStyleSheet("color:#474A51;")
        self.Table3.setObjectName("Table3")
        self.horizontalLayout_11.addWidget(self.Table3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.TopBarLeft, 0, QtCore.Qt.AlignLeft)
        self.tableWidgetPatients = QtWidgets.QTableWidget(self.TablePatients)
        self.tableWidgetPatients.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidgetPatients.setStyleSheet("border-radius:12px;\n"
"color: #474A51;")
        self.tableWidgetPatients.setObjectName("tableWidgetPatients")
        self.tableWidgetPatients.setColumnCount(6)
        self.tableWidgetPatients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 81))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetPatients.setHorizontalHeaderItem(5, item)
        self.verticalLayout_10.addWidget(self.tableWidgetPatients)
        self.verticalLayout_11.addWidget(self.TablePatients)
        self.stackedWidget.addWidget(self.ReportpagePatients)
        self.ReportpageDoc = QtWidgets.QWidget()
        self.ReportpageDoc.setMaximumSize(QtCore.QSize(778, 483))
        self.ReportpageDoc.setObjectName("ReportpageDoc")
        self.TableDoctors = QtWidgets.QWidget(self.ReportpageDoc)
        self.TableDoctors.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.TableDoctors.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TableDoctors.setObjectName("TableDoctors")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.TableDoctors)
        self.verticalLayout_14.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Label2 = QtWidgets.QLabel(self.TableDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Label2.setFont(font)
        self.Label2.setStyleSheet("color:#474A51;")
        self.Label2.setObjectName("Label2")
        self.verticalLayout_14.addWidget(self.Label2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TopBarRight2 = QtWidgets.QFrame(self.TableDoctors)
        self.TopBarRight2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarRight2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarRight2.setObjectName("TopBarRight2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.TopBarRight2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Edit2 = QtWidgets.QPushButton(self.TopBarRight2)
        self.Edit2.setText("")
        self.Edit2.setIcon(icon8)
        self.Edit2.setIconSize(QtCore.QSize(24, 24))
        self.Edit2.setObjectName("Edit2")
        self.Edit2.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.horizontalLayout_13.addWidget(self.Edit2)
        self.Delete2 = QtWidgets.QPushButton(self.TopBarRight2)
        self.Delete2.setText("")
        self.Delete2.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.Delete2.setIcon(icon9)
        self.Delete2.setIconSize(QtCore.QSize(24, 24))
        self.Delete2.setObjectName("Delete2")
        self.horizontalLayout_13.addWidget(self.Delete2)
        self.verticalLayout_14.addWidget(self.TopBarRight2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.TopBarLeft2 = QtWidgets.QFrame(self.TableDoctors)
        self.TopBarLeft2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarLeft2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarLeft2.setObjectName("TopBarLeft2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.TopBarLeft2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Tab1 = QtWidgets.QPushButton(self.TopBarLeft2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Tab1.setFont(font)
        self.Tab1.setStyleSheet("color:#474A51;")
        self.Tab1.setObjectName("Tab1")
        self.horizontalLayout_12.addWidget(self.Tab1)
        self.Tab2 = QtWidgets.QPushButton(self.TopBarLeft2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Tab2.setFont(font)
        self.Tab2.setStyleSheet("color:#474A51;")
        self.Tab2.setObjectName("Tab2")
        self.horizontalLayout_12.addWidget(self.Tab2)
        self.Tab3 = QtWidgets.QPushButton(self.TopBarLeft2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Tab3.setFont(font)
        self.Tab3.setStyleSheet("color:#474A51;")
        self.Tab3.setObjectName("Tab3")
        self.horizontalLayout_12.addWidget(self.Tab3)
        self.verticalLayout_14.addWidget(self.TopBarLeft2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tableWidgetDoc = QtWidgets.QTableWidget(self.TableDoctors)
        self.tableWidgetDoc.setStyleSheet("border-radius:12px;\n"
"color: #474A51;")
        self.tableWidgetDoc.setObjectName("tableWidgetDoc")
        self.tableWidgetDoc.setColumnCount(3)
        self.tableWidgetDoc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetDoc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetDoc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetDoc.setHorizontalHeaderItem(2, item)
        self.verticalLayout_14.addWidget(self.tableWidgetDoc)
        self.stackedWidget.addWidget(self.ReportpageDoc)
        self.ReportpageAppointment = QtWidgets.QWidget()
        self.ReportpageAppointment.setObjectName("ReportpageAppointment")
        self.widget = QtWidgets.QWidget(self.ReportpageAppointment)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 781, 491))
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Label3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.Label3.setFont(font)
        self.Label3.setStyleSheet("color:#474A51;")
        self.Label3.setObjectName("Label3")
        self.verticalLayout_15.addWidget(self.Label3)
        self.TopBarRight3 = QtWidgets.QFrame(self.widget)
        self.TopBarRight3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarRight3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarRight3.setObjectName("TopBarRight3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.TopBarRight3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Edit3 = QtWidgets.QPushButton(self.TopBarRight3)
        self.Edit3.setText("")
        self.Edit3.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.Edit3.setIcon(icon8)
        self.Edit3.setIconSize(QtCore.QSize(24, 24))
        self.Edit3.setObjectName("Edit3")
        self.horizontalLayout_15.addWidget(self.Edit3, 0, QtCore.Qt.AlignRight)
        self.Save = QtWidgets.QPushButton(self.TopBarRight3)
        self.Save.setText("")  # Не устанавливаем текст, так как использована иконка
        self.Save.setStyleSheet("""
                            QPushButton {
                                background-color: transparent;
                            }
                            QPushButton:hover {
                                background-color: lightgray;
                            }
                            QPushButton:pressed {
                                background-color: gray;
                            }
                        """)
        save_icon_path = "static/img/save.png"
        save_icon = QtGui.QIcon()
        save_icon.addPixmap(QtGui.QPixmap("static/img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save.setIcon(save_icon)
        self.Save.setIconSize(QtCore.QSize(24, 24))  # Задайте размер иконки
        self.Save.setObjectName("Save")  # Установите имя объекта
        self.horizontalLayout_15.addWidget(self.Save, 0, QtCore.Qt.AlignRight)  # Добавляем кнопку в нужный layout
        self.Delete3 = QtWidgets.QPushButton(self.TopBarRight3)
        self.Delete3.setText("")
        self.Delete3.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.Delete3.setIcon(icon9)
        self.Delete3.setIconSize(QtCore.QSize(24, 24))
        self.Delete3.setObjectName("Delete3")
        self.horizontalLayout_15.addWidget(self.Delete3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.TopBarRight3, 0, QtCore.Qt.AlignRight)
        self.TopBarLeft3 = QtWidgets.QFrame(self.widget)
        self.TopBarLeft3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarLeft3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarLeft3.setObjectName("TopBarLeft3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.TopBarLeft3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Bt1 = QtWidgets.QPushButton(self.TopBarLeft3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Bt1.setFont(font)
        self.Bt1.setStyleSheet("color:#474A51;")
        self.Bt1.setObjectName("Bt1")
        self.Bt1.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.horizontalLayout_14.addWidget(self.Bt1, 0, QtCore.Qt.AlignLeft)
        self.Bt2 = QtWidgets.QPushButton(self.TopBarLeft3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        self.Bt2.setFont(font)
        self.Bt2.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.Bt2.setStyleSheet("color:#474A51;")
        self.Bt2.setObjectName("Bt2")
        self.horizontalLayout_14.addWidget(self.Bt2, 0, QtCore.Qt.AlignLeft)
        self.Bt3 = QtWidgets.QPushButton(self.TopBarLeft3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Bt3.setFont(font)
        self.Bt3.setStyleSheet("color:#474A51;")
        self.Bt3.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                    }
                """)
        self.Bt3.setObjectName("Bt3")
        self.horizontalLayout_14.addWidget(self.Bt3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_15.addWidget(self.TopBarLeft3, 0, QtCore.Qt.AlignLeft)
        self.tableWidgetAppointment = QtWidgets.QTableWidget(self.widget)
        self.tableWidgetAppointment.setStyleSheet("border-radius:12px;\n"
"color: #474A51;")
        self.tableWidgetAppointment.setObjectName("tableWidgetAppointment")
        self.tableWidgetAppointment.setColumnCount(6)
        self.tableWidgetAppointment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidgetAppointment.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(71, 74, 84))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.verticalLayout_15.addWidget(self.tableWidgetAppointment)
        self.stackedWidget.addWidget(self.ReportpageAppointment)
        self.Labpage = QtWidgets.QWidget()
        self.Labpage.setObjectName("Labpage")
        self.LabName = QtWidgets.QLabel(self.Labpage)
        self.LabName.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.LabName.setFont(font)
        self.LabName.setStyleSheet("color:#474A51;")
        self.LabName.setObjectName("LabName")
        self.stackedWidget.addWidget(self.Labpage)
        self.Statisticpage = QtWidgets.QWidget()
        self.Statisticpage.setObjectName("Statisticpage")
        self.StatisticName = QtWidgets.QLabel(self.Statisticpage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.StatisticName.setFont(font)
        self.StatisticName.setStyleSheet("color:#474A51;")
        self.StatisticName.setObjectName("StatisticName")
        self.stackedWidget.addWidget(self.Statisticpage)
        self.Settingspage = QtWidgets.QWidget()
        self.Settingspage.setObjectName("Settingspage")
        self.SettingsName = QtWidgets.QLabel(self.Settingspage)
        self.SettingsName.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.SettingsName.setFont(font)
        self.SettingsName.setStyleSheet("color:#474A51;")
        self.SettingsName.setObjectName("SettingsName")
        self.stackedWidget.addWidget(self.Settingspage)
        self.Helppage = QtWidgets.QWidget()
        self.Helppage.setObjectName("Helppage")
        self.HelpName = QtWidgets.QLabel(self.Helppage)
        self.HelpName.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.HelpName.setFont(font)
        self.HelpName.setStyleSheet("color:#474A51;")
        self.HelpName.setObjectName("HelpName")
        self.stackedWidget.addWidget(self.Helppage)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.mainBodyContent)
        self.RightMenuDoctors = QtWidgets.QWidget(self.MainBody)
        self.RightMenuDoctors.setMaximumSize(QtCore.QSize(0, 16777215))
        self.RightMenuDoctors.setObjectName("RightMenuDoctors")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.RightMenuDoctors)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.RightMenuWidgetDoctors = QtWidgets.QWidget(self.RightMenuDoctors)
        self.RightMenuWidgetDoctors.setObjectName("RightMenuWidgetDoctors")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.RightMenuWidgetDoctors)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.FromForDoctors = QtWidgets.QFrame(self.RightMenuWidgetDoctors)
        self.FromForDoctors.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FromForDoctors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FromForDoctors.setObjectName("FromForDoctors")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.FromForDoctors)
        self.verticalLayout_12.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TopBarButtonDoctors = QtWidgets.QFrame(self.FromForDoctors)
        self.TopBarButtonDoctors.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarButtonDoctors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarButtonDoctors.setObjectName("TopBarButtonDoctors")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.TopBarButtonDoctors)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Doctors2 = QtWidgets.QPushButton(self.TopBarButtonDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Doctors2.setFont(font)
        self.Doctors2.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                        color:#474A51;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                        color:#474A51;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                        color:#474A51;
                    }
                """)
        self.Doctors2.setObjectName("Doctors2")
        self.horizontalLayout_10.addWidget(self.Doctors2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Patients2 = QtWidgets.QPushButton(self.TopBarButtonDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Patients2.setFont(font)
        self.Patients2.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                        color:#474A51;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                        color:#474A51;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                        color:#474A51;
                    }
                """)
        self.Patients2.setObjectName("Patients2")
        self.horizontalLayout_10.addWidget(self.Patients2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Dismiss2 = QtWidgets.QPushButton(self.TopBarButtonDoctors)
        self.Dismiss2.setText("")
        self.Dismiss2.setStyleSheet("""
                            QPushButton {
                                background-color: transparent;
                            }
                            QPushButton:hover {
                                background-color: lightgray;
                            }
                            QPushButton:pressed {
                                background-color: gray;
                            }
                        """)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("static/img/dismiss.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dismiss2.setIcon(icon10)
        self.Dismiss2.setIconSize(QtCore.QSize(12, 12))
        self.Dismiss2.setObjectName("Dismiss2")
        self.horizontalLayout_10.addWidget(self.Dismiss2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_12.addWidget(self.TopBarButtonDoctors, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.FIODoctors = QtWidgets.QLineEdit(self.FromForDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.FIODoctors.setFont(font)
        self.FIODoctors.setObjectName("FIODoctors")
        self.verticalLayout_12.addWidget(self.FIODoctors)
        self.Job = QtWidgets.QLineEdit(self.FromForDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Job.setFont(font)
        self.Job.setText("")
        self.Job.setObjectName("Job")
        self.verticalLayout_12.addWidget(self.Job)
        self.verticalLayout_13.addWidget(self.FromForDoctors, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AddDoctors = QtWidgets.QPushButton(self.RightMenuWidgetDoctors)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.AddDoctors.setFont(font)
        self.AddDoctors.setStyleSheet("QPushButton {\n"
"border-radius: 6px; \n"
"background-color: #207BFF;\n"
"color: white;\n"
"margin-top:10px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:cliked {\n"
"background-color:#0b5ed7;}")
        self.AddDoctors.setObjectName("AddDoctors")
        self.verticalLayout_13.addWidget(self.AddDoctors, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_9.addWidget(self.RightMenuWidgetDoctors, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.RightMenuDoctors, 0, QtCore.Qt.AlignLeft)
        self.RightMenu = QtWidgets.QWidget(self.MainBody)
        self.RightMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.RightMenu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.RightMenu.setSizeIncrement(QtCore.QSize(0, 0))
        self.RightMenu.setBaseSize(QtCore.QSize(0, 0))
        self.RightMenu.setObjectName("RightMenu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.RightMenu)
        self.verticalLayout_7.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.RightMenuWidget = QtWidgets.QWidget(self.RightMenu)
        self.RightMenuWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.RightMenuWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RightMenuWidget.setObjectName("RightMenuWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.RightMenuWidget)
        self.verticalLayout_8.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TopBarButton = QtWidgets.QFrame(self.RightMenuWidget)
        self.TopBarButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopBarButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopBarButton.setObjectName("TopBarButton")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.TopBarButton)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Patients = QtWidgets.QPushButton(self.TopBarButton)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Patients.setFont(font)
        self.Patients.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                        color:#474A51;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                        color:#474A51;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                        color:#474A51;
                    }
                """)
        self.Patients.setObjectName("Patients")
        self.horizontalLayout_8.addWidget(self.Patients)
        self.Doctors = QtWidgets.QPushButton(self.TopBarButton)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Doctors.setFont(font)
        self.Doctors.setStyleSheet("""
                    QPushButton {
                        background-color: transparent;
                        color:#474A51;
                    }
                    QPushButton:hover {
                        background-color: lightgray;
                        color:#474A51;
                    }
                    QPushButton:pressed {
                        background-color: gray;
                        color:#474A51;
                    }
                """)
        self.Doctors.setObjectName("Doctors")
        self.horizontalLayout_8.addWidget(self.Doctors)
        self.Dismiss = QtWidgets.QPushButton(self.TopBarButton)
        self.Dismiss.setText("")
        self.Dismiss.setStyleSheet("""
                                    QPushButton {
                                        background-color: transparent;
                                    }
                                    QPushButton:hover {
                                        background-color: lightgray;
                                    }
                                    QPushButton:pressed {
                                        background-color: gray;
                                    }
                                """)
        self.Dismiss.setIcon(icon10)
        self.Dismiss.setIconSize(QtCore.QSize(12, 12))
        self.Dismiss.setObjectName("Dismiss")
        self.horizontalLayout_8.addWidget(self.Dismiss, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8.addWidget(self.TopBarButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.FormForPatients = QtWidgets.QFrame(self.RightMenuWidget)
        self.FormForPatients.setMinimumSize(QtCore.QSize(356, 203))
        self.FormForPatients.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FormForPatients.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FormForPatients.setObjectName("FormForPatients")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.FormForPatients)
        self.verticalLayout_9.setContentsMargins(5, 10, 5, 10)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.FIO = QtWidgets.QLineEdit(self.FormForPatients)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.FIO.setFont(font)
        self.FIO.setObjectName("FIO")
        self.verticalLayout_9.addWidget(self.FIO)
        self.Birthday = QtWidgets.QLineEdit(self.FormForPatients)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Birthday.setFont(font)
        self.Birthday.setObjectName("Birthday")
        self.verticalLayout_9.addWidget(self.Birthday)
        self.Adres = QtWidgets.QLineEdit(self.FormForPatients)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Adres.sizePolicy().hasHeightForWidth())
        self.Adres.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Adres.setFont(font)
        self.Adres.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Adres.setObjectName("Adres")
        self.verticalLayout_9.addWidget(self.Adres)
        self.Phone = QtWidgets.QLineEdit(self.FormForPatients)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.Phone.setFont(font)
        self.Phone.setObjectName("Phone")
        self.verticalLayout_9.addWidget(self.Phone)
        self.Gender = QtWidgets.QFrame(self.FormForPatients)
        self.Gender.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Gender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Gender.setObjectName("Gender")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Gender)
        self.horizontalLayout_5.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Women = QtWidgets.QRadioButton(self.Gender)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Women.setFont(font)
        self.Women.setStyleSheet("")
        self.Women.setObjectName("Women")
        self.horizontalLayout_5.addWidget(self.Women)
        self.Man = QtWidgets.QRadioButton(self.Gender)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.Man.setFont(font)
        self.Man.setStyleSheet("")
        self.Man.setObjectName("Man")
        self.horizontalLayout_5.addWidget(self.Man)
        self.verticalLayout_9.addWidget(self.Gender, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout_8.addWidget(self.FormForPatients, 0, QtCore.Qt.AlignHCenter)
        self.AddPatients = QtWidgets.QPushButton(self.RightMenuWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.AddPatients.setFont(font)
        self.AddPatients.setStyleSheet("QPushButton {\n"
"border-radius: 6px; \n"
"background-color: #207BFF;\n"
"color: white;\n"
"margin-top:10px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:cliked {\n"
"background-color:#0b5ed7;}")

        self.AddPatients.setIconSize(QtCore.QSize(20, 20))
        self.AddPatients.setObjectName("AddPatients")
        self.verticalLayout_8.addWidget(self.AddPatients, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.RightMenuWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.RightMenu)
        self.verticalLayout.addWidget(self.MainBody)
        self.Footer = QtWidgets.QWidget(self.centralwidget)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.MyName = QtWidgets.QLabel(self.Footer)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.MyName.setFont(font)
        self.MyName.setStyleSheet("color:#474A51;")
        self.MyName.setObjectName("MyName")
        self.horizontalLayout_6.addWidget(self.MyName, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.Footer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MedSoft"))
        self.Logotip.setText(_translate("MainWindow", "MedSoft"))
        self.Name.setText(_translate("MainWindow", "Иванов Иван"))
        self.Report.setText(_translate("MainWindow", "Журнал учета"))
        self.Lab.setText(_translate("MainWindow", "Лаборатория"))
        self.Statistics.setText(_translate("MainWindow", "Статистика"))
        self.Help.setText(_translate("MainWindow", "Помощь"))
        self.Settings.setText(_translate("MainWindow", "Настройки"))
        self.Label.setText(_translate("MainWindow", "Список пациентов"))
        self.Table1.setText(_translate("MainWindow", "Пациенты"))
        self.Table2.setText(_translate("MainWindow", "Врачи"))
        self.Table3.setText(_translate("MainWindow", "Записи"))
        item = self.tableWidgetPatients.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetPatients.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableWidgetPatients.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата рождения"))
        item = self.tableWidgetPatients.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.tableWidgetPatients.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Пол"))
        item = self.tableWidgetPatients.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Номер телефона"))
        self.Label2.setText(_translate("MainWindow", "Список врачей"))
        self.Tab1.setText(_translate("MainWindow", "Пациенты"))
        self.Tab2.setText(_translate("MainWindow", "Врачи"))
        self.Tab3.setText(_translate("MainWindow", "Записи"))
        item = self.tableWidgetDoc.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetDoc.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableWidgetDoc.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Должность"))
        self.Label3.setText(_translate("MainWindow", "Журнал учета записей"))
        self.Bt1.setText(_translate("MainWindow", "Пациенты"))
        self.Bt2.setText(_translate("MainWindow", "Врачи"))
        self.Bt3.setText(_translate("MainWindow", "Записи"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Пациент"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Врач"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Время"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата обращения"))
        item = self.tableWidgetAppointment.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Прием"))
        self.LabName.setText(_translate("MainWindow", "Лаборатория"))
        self.StatisticName.setText(_translate("MainWindow", "Статистика"))
        self.SettingsName.setText(_translate("MainWindow", "Настройки"))
        self.HelpName.setText(_translate("MainWindow", "Помощь"))
        self.Doctors2.setText(_translate("MainWindow", "Врачи"))
        self.Patients2.setText(_translate("MainWindow", "Пациенты"))
        self.FIODoctors.setPlaceholderText(_translate("MainWindow", "ФИО"))
        self.Job.setPlaceholderText(_translate("MainWindow", "Должность"))
        self.AddDoctors.setText(_translate("MainWindow", "Добавить"))
        self.Patients.setText(_translate("MainWindow", "Пациенты"))
        self.Doctors.setText(_translate("MainWindow", "Врачи"))
        self.FIO.setPlaceholderText(_translate("MainWindow", "ФИО"))
        self.Birthday.setPlaceholderText(_translate("MainWindow", "Дата рождения"))
        self.Adres.setPlaceholderText(_translate("MainWindow", "Адрес"))
        self.Phone.setPlaceholderText(_translate("MainWindow", "Номер телефона"))
        self.Women.setText(_translate("MainWindow", "Ж"))
        self.Man.setText(_translate("MainWindow", "М"))
        self.AddPatients.setText(_translate("MainWindow", "Добавить"))
        self.MyName.setText(_translate("MainWindow", "Daria Zamiralova 2024"))
        self.searchLineEdit.setPlaceholderText("ID пациента")  # Подсказка в поле ввода


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
